#!/bin/bash
set -e
set -u

rm -rf platforms/ plugins/
mkdir platforms plugins
cordova platform add ios
cordova plugin add org.apache.cordova.file org.apache.cordova.file-transfer org.apache.cordova.inappbrowser org.apache.cordova.statusbar org.chromium.zip
